apiVersion: kafka.strimzi.io/v1beta2

kind: Kafka

metadata:

 name: kafka

spec:

 kafka:

   version: 3.2.0

   replicas: 2

   listeners:

     - name: plain

       port: 9098

       type: internal

       tls: false

   config:
     num.partitions: 5

     offsets.topic.replication.factor: 1

     transaction.state.log.replication.factor: 1

     transaction.state.log.min.isr: 1

     default.replication.factor: 1

     min.insync.replicas: 1

     inter.broker.protocol.version: "3.2"
     log.message.format.version: "3.2"
     offsets.topic.num.partitions: 50
     message.max.bytes: 25000000
     replica.fetch.max.bytes: 25000000
     max.partition.fetch.bytes: 25000000



   storage:

     type: ephemeral

 zookeeper:

   replicas: 3

   storage:

     type: ephemeral

 entityOperator:

   topicOperator: {}

   userOperator: {}
